workflows:
  android-workflow:
    name: PGNEWS Fast Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: | 
          # O comando abaixo ignora travas de versão e instala tudo do zero
          npm install --no-package-lock
          npm install -g @capacitor/cli
      
      - name: Build web project
        script: |
          # CI=false impede que avisos de CSS travem o processo
          CI=false npx vite build
      
      - name: Cap Sync and Add Android
        script: |
          # Cria a estrutura mobile se não existir
          npx cap add android || true
          npx cap sync android
      
      - name: Build Android APK
        script: |
          # Compila o arquivo final
          cd android
          ./gradlew assembleDebug
    
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
